services:
  migrations:
    build: .
    command: python3 manage.py migrate
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./kids_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - migrations