version: "3"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./kids_app:/app
    ports:
      - "8000:80"
    environment:
      - musescoreDirectPNGPath=
      - musicxmlPath=
      - lilypondPath=/usr/bin/lilypond
