version: "3"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./kids_app:/app
    ports:
      - "80:80"
    environment:
      - musescoreDirectPNGPath=
      - musicxmlPath=
      - lilypondPath=
